/**
 * Ürün kataloğu demo verisi — 12 hazır web sitesi, 8 uygulama/sistem, 6 hizmet paketi.
 * Fiyatlar kuruş cinsindendir (₺24.900 → 2490000).
 */

export type SeedProduct = {
  slug: string;
  name: string;
  type: "website" | "app" | "webapp" | "system" | "template" | "service";
  category: string;
  shortDesc: string;
  description: string;
  features: string[];
  useCases: string[];
  modules: string[];
  techSpecs: Record<string, string>;
  requirements?: string;
  basePrice: number;
  comparePrice?: number;
  technologies: string[];
  platforms: string[];
  designStyle: string;
  deliveryDays: number;
  hasAdminPanel?: boolean;
  includesSetup?: boolean;
  includesSource?: boolean;
  multiLanguage?: boolean;
  hasPayment?: boolean;
  isFeatured?: boolean;
  isBestSeller?: boolean;
  isNew?: boolean;
  salesCount: number;
  viewCount: number;
  /** Genişletilmiş ve özel lisansın taban fiyata ekleyeceği fark (kuruş). */
  licenses: { genisletilmis: number; ozel: number };
};

const wpSpecs = () => ({
  "Yazılım dili": "PHP 8.2",
  Framework: "WordPress 6.x",
  Veritabanı: "MySQL 8.0",
  "Responsive tasarım": "Var",
  "Tarayıcı uyumluluğu": "Chrome, Safari, Firefox, Edge (son 2 sürüm)",
  "API desteği": "REST API",
  "SEO altyapısı": "Schema.org, sitemap, meta yönetimi",
  Dokümantasyon: "PDF kılavuz + kurulum videosu",
});

const nextSpecs = (extra: Record<string, string> = {}) => ({
  "Yazılım dili": "TypeScript",
  Framework: "Next.js 15 (App Router)",
  Veritabanı: "PostgreSQL 16",
  "Responsive tasarım": "Var",
  "Tarayıcı uyumluluğu": "Chrome, Safari, Firefox, Edge (son 2 sürüm)",
  "API desteği": "REST + Server Actions",
  "SEO altyapısı": "Dinamik meta, sitemap, schema.org",
  Güvenlik: "Rol tabanlı yetki, CSRF koruması, hız sınırlama",
  ...extra,
});

const mobileSpecs = (framework: string, extra: Record<string, string> = {}) => ({
  "Yazılım dili": framework === "Flutter" ? "Dart 3" : "TypeScript",
  Framework: framework,
  Veritabanı: "PostgreSQL + nesne depolama",
  Platformlar: "Android 8+, iOS 14+",
  "Bildirim sistemi": "Push bildirim altyapısı hazır",
  "API desteği": "REST API",
  Dokümantasyon: "Kurulum ve mağaza yayın rehberi",
  ...extra,
});

export const PRODUCTS: SeedProduct[] = [
  // ---------------------------- Hazır web siteleri ----------------------------
  {
    slug: "atlas-kurumsal-web-sitesi",
    name: "Atlas Kurumsal Web Sitesi",
    type: "website",
    category: "kurumsal-web-siteleri",
    shortDesc: "Kurumsal firmalar için sade, hızlı ve güven veren tanıtım sitesi.",
    description:
      "Atlas, kurumsal firmaların dijital vitrinini birkaç gün içinde kurmak için hazırlanmış bir web sitesi paketidir. Hizmetlerinizi, referanslarınızı ve ekibinizi tanıtan bölümler hazır gelir; yönetim panelinden içerikleri kod bilgisi olmadan düzenlersiniz. Sayfa hızı ve Core Web Vitals ölçütleri gözetilerek geliştirildiği için mobilde de hızlı açılır.",
    features: ["Hizmet ve referans bölümleri", "Ekip tanıtım sayfası", "Blog ve duyuru modülü", "İletişim formu ve harita", "Çoklu dil altyapısı", "SEO ayarları paneli"],
    useCases: ["Mühendislik ve danışmanlık firmaları", "Üretim ve sanayi şirketleri", "Hukuk ve mali müşavirlik büroları"],
    modules: ["Sayfa yönetimi", "Blog", "Referanslar", "Ekip", "Form kayıtları", "SEO"],
    techSpecs: wpSpecs(),
    requirements: "PHP 8.1+, MySQL 5.7+, en az 1 GB disk alanı",
    basePrice: 1490000,
    comparePrice: 1990000,
    technologies: ["wordpress", "php", "mysql"],
    platforms: ["web"],
    designStyle: "kurumsal",
    deliveryDays: 2,
    hasAdminPanel: true,
    multiLanguage: true,
    isFeatured: true,
    isBestSeller: true,
    salesCount: 148,
    viewCount: 5210,
    licenses: { genisletilmis: 1200000, ozel: 4900000 },
  },
  {
    slug: "vitrin-eticaret-sitesi",
    name: "Vitrin E-Ticaret Sitesi",
    type: "website",
    category: "eticaret-siteleri",
    shortDesc: "Sanal POS, kargo ve stok yönetimi hazır gelen tam donanımlı mağaza.",
    description:
      "Vitrin, ürün satışına hemen başlamak isteyen işletmeler için kurgulanmış bir e-ticaret paketidir. Sanal POS ve kapıda ödeme, kargo entegrasyonu, kupon ve kampanya yönetimi kutudan çıkar. Sepet ve ödeme adımları dönüşüm odaklı sadeleştirilmiştir; mobilde tek elle tamamlanabilen bir ödeme akışı sunar.",
    features: ["Sanal POS ve taksit desteği", "Kargo entegrasyonu", "Varyasyonlu ürün yönetimi", "Kupon ve kampanya motoru", "Terk edilen sepet hatırlatması", "Çoklu para birimi"],
    useCases: ["Moda ve tekstil mağazaları", "Kozmetik ve bakım markaları", "Butik üretici ve el emeği satıcıları"],
    modules: ["Ürün yönetimi", "Sipariş yönetimi", "Kargo", "Kupon", "Müşteri yönetimi", "Raporlar"],
    techSpecs: wpSpecs(),
    requirements: "PHP 8.1+, MySQL 8+, SSL sertifikası zorunlu",
    basePrice: 2490000,
    comparePrice: 3290000,
    technologies: ["wordpress", "woocommerce", "php"],
    platforms: ["web", "pwa"],
    designStyle: "minimal",
    deliveryDays: 3,
    hasAdminPanel: true,
    multiLanguage: true,
    hasPayment: true,
    isFeatured: true,
    isBestSeller: true,
    salesCount: 216,
    viewCount: 8940,
    licenses: { genisletilmis: 1800000, ozel: 7500000 },
  },
  {
    slug: "sofra-restoran-web-sitesi",
    name: "Sofra Restoran Web Sitesi",
    type: "website",
    category: "restoran-siteleri",
    shortDesc: "Dijital menü, rezervasyon ve online sipariş içeren restoran sitesi.",
    description:
      "Sofra, restoran ve kafelerin menülerini dijitalleştirip masa rezervasyonu ve paket sipariş almasını sağlar. QR menü, günün menüsü, şube yönetimi ve çalışma saatleri modülleri hazırdır. Menü fiyatlarını panelden güncellediğinizde QR menü de anında güncellenir.",
    features: ["QR dijital menü", "Masa rezervasyon formu", "Paket sipariş modülü", "Şube ve çalışma saatleri", "Galeri ve şef tanıtımı", "Harita entegrasyonu"],
    useCases: ["Restoran ve kafeler", "Kahvaltı salonları", "Çok şubeli zincir işletmeler"],
    modules: ["Menü yönetimi", "Rezervasyon", "Sipariş", "Şube yönetimi", "Galeri"],
    techSpecs: nextSpecs({ "Çoklu dil": "TR / EN hazır" }),
    requirements: "Node.js 20+, PostgreSQL 14+ veya yönetilen veritabanı",
    basePrice: 1790000,
    comparePrice: 2290000,
    technologies: ["nextjs", "react", "postgresql"],
    platforms: ["web", "pwa"],
    designStyle: "renkli",
    deliveryDays: 2,
    hasAdminPanel: true,
    multiLanguage: true,
    isFeatured: true,
    isNew: true,
    salesCount: 87,
    viewCount: 4120,
    licenses: { genisletilmis: 1400000, ozel: 5400000 },
  },
  {
    slug: "medica-klinik-web-sitesi",
    name: "Medica Klinik Web Sitesi",
    type: "website",
    category: "klinik-saglik-siteleri",
    shortDesc: "Online randevu ve hasta bilgilendirme odaklı sağlık sitesi.",
    description:
      "Medica, klinik ve muayenehaneler için hazırlanmış, randevu almayı tek adıma indiren bir sitedir. Doktor profilleri, tedavi sayfaları, hasta yorumları ve sağlık turizmine uygun çoklu dil yapısı içerir. Form alanları KVKK aydınlatma onayıyla birlikte gelir.",
    features: ["Online randevu takvimi", "Doktor ve tedavi profilleri", "Hasta yorumları", "Öncesi/sonrası galerisi", "Çoklu dil (TR/EN/AR)", "KVKK uyumlu form onayları"],
    useCases: ["Diş klinikleri", "Estetik ve saç ekim merkezleri", "Fizik tedavi ve rehabilitasyon"],
    modules: ["Randevu", "Doktorlar", "Tedaviler", "Yorumlar", "Blog", "Form kayıtları"],
    techSpecs: nextSpecs({ "Çoklu dil": "TR / EN / AR" }),
    requirements: "Node.js 20+, PostgreSQL 14+",
    basePrice: 2190000,
    comparePrice: 2790000,
    technologies: ["nextjs", "react", "postgresql"],
    platforms: ["web"],
    designStyle: "minimal",
    deliveryDays: 3,
    hasAdminPanel: true,
    multiLanguage: true,
    isFeatured: true,
    salesCount: 132,
    viewCount: 6380,
    licenses: { genisletilmis: 1600000, ozel: 6900000 },
  },
  {
    slug: "arsa-emlak-portali",
    name: "Arsa Emlak Portalı",
    type: "website",
    category: "emlak-siteleri",
    shortDesc: "Harita üzerinde ilan arama ve danışman yönetimi olan emlak sitesi.",
    description:
      "Arsa, emlak ofisleri için ilan yönetimini ve müşteri taleplerini tek yerde toplar. İlanlar harita üzerinde filtrelenebilir; her danışmanın kendi portföy sayfası olur. Talep formundan gelen kayıtlar ilgili danışmana otomatik atanır.",
    features: ["Harita üzerinde ilan arama", "Gelişmiş filtreleme", "Danışman portföy sayfaları", "İlan karşılaştırma", "Talep formu ve otomatik atama", "360° görsel desteği"],
    useCases: ["Emlak ofisleri", "Gayrimenkul yatırım şirketleri", "Proje satış ofisleri"],
    modules: ["İlan yönetimi", "Danışmanlar", "Talepler", "Harita", "Blog"],
    techSpecs: nextSpecs({ Harita: "OpenStreetMap tabanlı" }),
    requirements: "Node.js 20+, PostgreSQL 14+",
    basePrice: 2690000,
    technologies: ["nextjs", "react", "postgresql"],
    platforms: ["web"],
    designStyle: "kurumsal",
    deliveryDays: 4,
    hasAdminPanel: true,
    salesCount: 64,
    viewCount: 3110,
    licenses: { genisletilmis: 1900000, ozel: 7900000 },
  },
  {
    slug: "marina-otel-rezervasyon-sitesi",
    name: "Marina Otel Rezervasyon Sitesi",
    type: "website",
    category: "otel-turizm-siteleri",
    shortDesc: "Oda müsaitliği, fiyat takvimi ve online rezervasyon içeren otel sitesi.",
    description:
      "Marina, otel ve butik konaklama işletmelerinin doğrudan rezervasyon almasını sağlar. Sezonluk fiyat takvimi, oda tipleri, ek hizmetler ve iptal politikası yönetimi hazır gelir. Aracı platformlara komisyon ödemeden kendi kanalınızdan satış yapmanız için kurgulanmıştır.",
    features: ["Oda müsaitlik takvimi", "Sezonluk fiyatlandırma", "Online rezervasyon ve ön ödeme", "Ek hizmet satışı", "Çoklu dil ve para birimi", "İptal politikası yönetimi"],
    useCases: ["Butik oteller", "Apart ve pansiyonlar", "Villa kiralama işletmeleri"],
    modules: ["Odalar", "Rezervasyon", "Fiyat takvimi", "Ek hizmetler", "Misafir yorumları"],
    techSpecs: nextSpecs({ "Çoklu para birimi": "TRY / EUR / USD" }),
    requirements: "Node.js 20+, PostgreSQL 14+",
    basePrice: 2890000,
    comparePrice: 3490000,
    technologies: ["nextjs", "react", "postgresql"],
    platforms: ["web"],
    designStyle: "premium",
    deliveryDays: 4,
    hasAdminPanel: true,
    multiLanguage: true,
    hasPayment: true,
    salesCount: 71,
    viewCount: 3560,
    licenses: { genisletilmis: 2100000, ozel: 8400000 },
  },
  {
    slug: "akademi-egitim-sitesi",
    name: "Akademi Eğitim Sitesi",
    type: "website",
    category: "egitim-siteleri",
    shortDesc: "Kurs satışı, video ders ve öğrenci paneli olan eğitim platformu.",
    description:
      "Akademi, kurs ve eğitim kurumlarının programlarını tanıtıp online satış yapmasını sağlar. Video ders altyapısı, ilerleme takibi, sınav modülü ve sertifika üretimi içerir. Eğitmenler kendi panelinden içerik yükleyebilir.",
    features: ["Kurs ve ders yönetimi", "Video ders oynatıcı", "İlerleme takibi", "Sınav ve sertifika", "Eğitmen paneli", "Taksitli ödeme desteği"],
    useCases: ["Özel kurslar ve dershaneler", "Online eğitim girişimleri", "Kurumsal eğitim birimleri"],
    modules: ["Kurslar", "Dersler", "Sınavlar", "Sertifikalar", "Öğrenciler", "Ödemeler"],
    techSpecs: nextSpecs({ Video: "HLS uyumlu, dış oynatıcı entegrasyonu" }),
    requirements: "Node.js 20+, PostgreSQL 14+, video için nesne depolama",
    basePrice: 3290000,
    technologies: ["nextjs", "react", "nodejs", "postgresql"],
    platforms: ["web", "pwa"],
    designStyle: "minimal",
    deliveryDays: 5,
    hasAdminPanel: true,
    hasPayment: true,
    isNew: true,
    salesCount: 53,
    viewCount: 2870,
    licenses: { genisletilmis: 2400000, ozel: 9500000 },
  },
  {
    slug: "gundem-haber-portali",
    name: "Gündem Haber Portalı",
    type: "website",
    category: "haber-blog-siteleri",
    shortDesc: "Yüksek trafiğe hazır, reklam alanları tanımlı haber sitesi.",
    description:
      "Gündem, haber siteleri için hızlı sayfa açılışını ve reklam gelirini önceleyen bir yapı sunar. Manşet yönetimi, kategori ve yazar sayfaları, anket ve son dakika şeridi hazırdır. Artımlı yeniden oluşturma sayesinde yoğun trafikte de sunucu yükü düşük kalır.",
    features: ["Manşet ve sürmanşet yönetimi", "Son dakika şeridi", "Reklam alanı yönetimi", "Yazar sayfaları", "Anket modülü", "Haber ajansı akışına uygun yapı"],
    useCases: ["Yerel haber siteleri", "Sektörel yayınlar", "Dergi ve içerik yayıncıları"],
    modules: ["Haberler", "Kategoriler", "Yazarlar", "Reklamlar", "Anketler"],
    techSpecs: nextSpecs({ Önbellekleme: "ISR + CDN uyumlu" }),
    requirements: "Node.js 20+, PostgreSQL 14+",
    basePrice: 1990000,
    comparePrice: 2490000,
    technologies: ["nextjs", "react", "postgresql"],
    platforms: ["web"],
    designStyle: "minimal",
    deliveryDays: 3,
    hasAdminPanel: true,
    salesCount: 45,
    viewCount: 2240,
    licenses: { genisletilmis: 1500000, ozel: 5900000 },
  },
  {
    slug: "studyo-portfoy-sitesi",
    name: "Stüdyo Portföy Sitesi",
    type: "website",
    category: "portfoy-siteleri",
    shortDesc: "Fotoğrafçı, tasarımcı ve stüdyolar için görsel odaklı portföy.",
    description:
      "Stüdyo, işini görselleriyle anlatan profesyoneller için hazırlanmıştır. Proje galerileri, vaka çalışması sayfaları ve teklif formu içerir. Büyük görsellerde otomatik optimizasyon ve tembel yükleme uygulanır.",
    features: ["Proje galerileri", "Vaka çalışması sayfaları", "Görsel optimizasyonu", "Koyu ve açık tema", "Teklif formu", "Sosyal medya akışı alanı"],
    useCases: ["Fotoğraf stüdyoları", "Grafik ve mimari tasarımcılar", "Video prodüksiyon ekipleri"],
    modules: ["Projeler", "Kategoriler", "Hakkımda", "İletişim"],
    techSpecs: nextSpecs(),
    requirements: "Node.js 20+, herhangi bir Node uyumlu hosting",
    basePrice: 990000,
    comparePrice: 1390000,
    technologies: ["nextjs", "react", "html-css-js"],
    platforms: ["web"],
    designStyle: "koyu",
    deliveryDays: 1,
    hasAdminPanel: true,
    salesCount: 119,
    viewCount: 4680,
    licenses: { genisletilmis: 900000, ozel: 3900000 },
  },
  {
    slug: "donusum-landing-page-seti",
    name: "Dönüşüm Landing Page Seti",
    type: "website",
    category: "landing-page-tasarimlari",
    shortDesc: "Reklam kampanyaları için A/B testine uygun 6 açılış sayfası.",
    description:
      "Dönüşüm seti, reklam kampanyalarında kullanılmak üzere hazırlanmış altı farklı açılış sayfası içerir. Form, WhatsApp ve arama butonu varyantlarıyla gelir; dönüşüm olayları hazır tanımlıdır. Hızlı açılış için kritik CSS satır içine gömülüdür.",
    features: ["6 farklı sayfa varyantı", "A/B test yapısı", "Form, WhatsApp ve arama butonları", "Dönüşüm olayı tanımları", "Hafif ve bağımsız kod", "Kolay renk ve metin değişimi"],
    useCases: ["Reklam kampanyaları", "Ürün lansmanları", "Potansiyel müşteri toplama"],
    modules: ["Sayfa varyantları", "Form kayıtları", "Olay takibi"],
    techSpecs: {
      "Yazılım dili": "HTML, CSS, JavaScript",
      Framework: "Bağımsız (framework gerektirmez)",
      "Responsive tasarım": "Var",
      "Tarayıcı uyumluluğu": "Chrome, Safari, Firefox, Edge",
      Dokümantasyon: "PDF kılavuz",
      "Kaynak kod": "Tam kaynak kod dahil",
    },
    requirements: "Herhangi bir statik hosting",
    basePrice: 690000,
    technologies: ["html-css-js"],
    platforms: ["web"],
    designStyle: "renkli",
    deliveryDays: 1,
    includesSource: true,
    salesCount: 203,
    viewCount: 7420,
    licenses: { genisletilmis: 600000, ozel: 2400000 },
  },
  {
    slug: "zaman-randevu-sitesi",
    name: "Zaman Randevu Sitesi",
    type: "website",
    category: "randevu-sistemleri",
    shortDesc: "Personel bazlı takvim ve online ödemeli randevu sistemi.",
    description:
      "Zaman, randevuyla çalışan tüm işletmeler için hazır bir sistemdir. Hizmet süreleri, personel takvimleri, mola tanımları ve kapora tahsilatı desteklenir. Müşteriye otomatik hatırlatma gönderimi için e-posta ve SMS altyapısı içerir.",
    features: ["Personel bazlı takvim", "Hizmet süresi ve mola tanımı", "Kapora tahsilatı", "Otomatik hatırlatma", "İptal ve erteleme", "Takvim senkronizasyonu"],
    useCases: ["Kuaför ve güzellik salonları", "Danışmanlık hizmetleri", "Servis ve bakım firmaları"],
    modules: ["Randevular", "Personel", "Hizmetler", "Ödemeler", "Hatırlatmalar"],
    techSpecs: nextSpecs(),
    requirements: "Node.js 20+, PostgreSQL 14+",
    basePrice: 2390000,
    technologies: ["nextjs", "react", "postgresql"],
    platforms: ["web", "pwa"],
    designStyle: "minimal",
    deliveryDays: 3,
    hasAdminPanel: true,
    hasPayment: true,
    salesCount: 96,
    viewCount: 4030,
    licenses: { genisletilmis: 1700000, ozel: 6900000 },
  },
  {
    slug: "pazar-cok-saticili-pazaryeri",
    name: "Pazar Çok Satıcılı Pazaryeri",
    type: "website",
    category: "pazaryeri-siteleri",
    shortDesc: "Satıcı paneli, komisyon ve hakediş yönetimi olan pazaryeri altyapısı.",
    description:
      "Pazar, birden fazla satıcının ürün sattığı bir pazaryeri kurmak için gereken modülleri içerir. Satıcı başvurusu, komisyon oranları, hakediş hesaplaması ve ödeme dağıtımı yönetilebilir. Satıcılar kendi panelinden ürün ve sipariş yönetir.",
    features: ["Satıcı başvuru ve onay akışı", "Satıcı paneli", "Komisyon ve hakediş yönetimi", "Toplu ürün içe aktarma", "Satıcı puanlaması", "Çoklu kargo yönetimi"],
    useCases: ["Sektörel pazaryerleri", "Yerel üretici platformları", "Kurumsal tedarik pazaryerleri"],
    modules: ["Satıcılar", "Ürünler", "Siparişler", "Komisyon", "Hakediş", "Raporlar"],
    techSpecs: nextSpecs({ Ödeme: "Pazaryeri ödeme dağıtımına uygun" }),
    requirements: "Node.js 20+, PostgreSQL 14+, nesne depolama",
    basePrice: 5490000,
    comparePrice: 6900000,
    technologies: ["nextjs", "nodejs", "postgresql", "react"],
    platforms: ["web"],
    designStyle: "kurumsal",
    deliveryDays: 7,
    hasAdminPanel: true,
    hasPayment: true,
    multiLanguage: true,
    isFeatured: true,
    salesCount: 28,
    viewCount: 3890,
    licenses: { genisletilmis: 3900000, ozel: 14900000 },
  },

  // ---------------------------- Uygulamalar ve sistemler ----------------------------
  {
    slug: "sepetim-eticaret-mobil-uygulamasi",
    name: "Sepetim E-Ticaret Mobil Uygulaması",
    type: "app",
    category: "eticaret-uygulamalari",
    shortDesc: "iOS ve Android için hazır, mağazanıza bağlanan alışveriş uygulaması.",
    description:
      "Sepetim, mevcut e-ticaret sitenizin mobil uygulamasını haftalar yerine günler içinde yayına almanızı sağlar. Ürün listeleme, sepet, ödeme, sipariş takibi ve bildirim akışları hazırdır. WooCommerce veya kendi REST API'nize bağlanabilir.",
    features: ["Ürün ve kategori akışı", "Sepet ve ödeme", "Sipariş takibi", "Anlık bildirim", "Favoriler", "Kampanya ekranları"],
    useCases: ["Mevcut e-ticaret siteleri", "Yeni kurulan markalar", "Sadakat programı yürüten mağazalar"],
    modules: ["Ürünler", "Sepet", "Ödeme", "Siparişler", "Bildirimler", "Profil"],
    techSpecs: mobileSpecs("Flutter 3.x", { "Ödeme entegrasyonu": "Sanal POS entegrasyonu hazır" }),
    requirements: "Flutter 3.x geliştirme ortamı, mağaza geliştirici hesapları",
    basePrice: 4490000,
    comparePrice: 5490000,
    technologies: ["flutter", "nodejs"],
    platforms: ["android", "ios"],
    designStyle: "minimal",
    deliveryDays: 6,
    hasAdminPanel: true,
    hasPayment: true,
    includesSource: true,
    isFeatured: true,
    isBestSeller: true,
    salesCount: 92,
    viewCount: 7150,
    licenses: { genisletilmis: 3200000, ozel: 12900000 },
  },
  {
    slug: "hizli-siparis-restoran-uygulamasi",
    name: "Hızlı Sipariş Restoran Uygulaması",
    type: "app",
    category: "restoran-siparis-uygulamalari",
    shortDesc: "Paket sipariş, masa siparişi ve kurye takibi olan restoran uygulaması.",
    description:
      "Hızlı Sipariş, restoranların aracı platformlara komisyon ödemeden kendi siparişlerini almasını sağlar. Müşteri uygulaması, mutfak ekranı ve kurye takibi birlikte gelir. Sipariş durumu değiştikçe müşteriye bildirim gider.",
    features: ["Paket ve masa siparişi", "Mutfak ekranı", "Kurye takibi", "Adres yönetimi", "Kampanya kodları", "Sipariş bildirimleri"],
    useCases: ["Restoran ve kafeler", "Zincir işletmeler", "Bulut mutfaklar"],
    modules: ["Menü", "Siparişler", "Mutfak", "Kurye", "Müşteriler"],
    techSpecs: mobileSpecs("Flutter 3.x"),
    requirements: "Flutter 3.x, Node.js 20+ API sunucusu",
    basePrice: 3890000,
    technologies: ["flutter", "nodejs", "postgresql"],
    platforms: ["android", "ios"],
    designStyle: "renkli",
    deliveryDays: 6,
    hasAdminPanel: true,
    isNew: true,
    salesCount: 47,
    viewCount: 3320,
    licenses: { genisletilmis: 2800000, ozel: 11500000 },
  },
  {
    slug: "randevum-mobil-uygulamasi",
    name: "Randevum Mobil Uygulaması",
    type: "app",
    category: "randevu-uygulamalari",
    shortDesc: "Salon ve kliniklerin müşterilerine sunduğu randevu uygulaması.",
    description:
      "Randevum, müşterilerinizin uygun saatleri görüp randevu almasını sağlar. Personel seçimi, hizmet süresi hesabı ve hatırlatma bildirimleri içerir. İşletme sahibi için gün sonu ve doluluk raporları sunar.",
    features: ["Uygun saat görüntüleme", "Personel seçimi", "Hatırlatma bildirimi", "Randevu geçmişi", "Puanlama", "Doluluk raporu"],
    useCases: ["Kuaför ve güzellik salonları", "Diş ve estetik klinikleri", "Veteriner klinikleri"],
    modules: ["Randevular", "Personel", "Hizmetler", "Bildirimler", "Raporlar"],
    techSpecs: mobileSpecs("React Native 0.74"),
    requirements: "React Native geliştirme ortamı, REST API sunucusu",
    basePrice: 3290000,
    comparePrice: 3990000,
    technologies: ["react-native", "nodejs"],
    platforms: ["android", "ios"],
    designStyle: "minimal",
    deliveryDays: 5,
    hasAdminPanel: true,
    salesCount: 61,
    viewCount: 2980,
    licenses: { genisletilmis: 2400000, ozel: 9800000 },
  },
  {
    slug: "rota-kurye-teslimat-sistemi",
    name: "Rota Kurye ve Teslimat Sistemi",
    type: "app",
    category: "kurye-teslimat-sistemleri",
    shortDesc: "Canlı konum takibi ve rota optimizasyonu olan teslimat sistemi.",
    description:
      "Rota, kendi kurye ekibini yöneten işletmeler için geliştirilmiştir. Kurye uygulaması, yönetim paneli ve müşteri takip ekranı birlikte gelir. Teslimat kanıtı olarak fotoğraf ve imza alınabilir.",
    features: ["Canlı konum takibi", "Rota optimizasyonu", "Teslimat kanıtı (fotoğraf/imza)", "Kurye performans raporu", "Toplu görev atama", "Müşteri takip bağlantısı"],
    useCases: ["Kargo ve dağıtım firmaları", "Su ve gıda dağıtımı", "Kendi kuryesini yöneten e-ticaret"],
    modules: ["Görevler", "Kuryeler", "Rotalar", "Teslimatlar", "Raporlar"],
    techSpecs: mobileSpecs("Flutter 3.x", { Harita: "Harita servisi entegrasyonu hazır" }),
    requirements: "Flutter 3.x, harita servisi anahtarı, Node.js API",
    basePrice: 4990000,
    technologies: ["flutter", "nodejs", "postgresql"],
    platforms: ["android", "ios", "web"],
    designStyle: "kurumsal",
    deliveryDays: 8,
    hasAdminPanel: true,
    salesCount: 24,
    viewCount: 2140,
    licenses: { genisletilmis: 3600000, ozel: 14500000 },
  },
  {
    slug: "formda-fitness-uygulamasi",
    name: "Formda Fitness Uygulaması",
    type: "app",
    category: "fitness-uygulamalari",
    shortDesc: "Antrenman planı, ölçüm takibi ve üyelik satışı olan spor uygulaması.",
    description:
      "Formda, spor salonları ve kişisel antrenörler için üye takibini dijitalleştirir. Antrenman ve beslenme planı atama, ölçüm geçmişi ve abonelik satışı içerir. Antrenör panelinden tüm üyeler tek ekrandan izlenir.",
    features: ["Antrenman planı atama", "Ölçüm ve ilerleme takibi", "Beslenme planı", "Abonelik satışı", "Ders rezervasyonu", "Antrenör paneli"],
    useCases: ["Spor salonları", "Kişisel antrenörler", "Online koçluk hizmetleri"],
    modules: ["Üyeler", "Planlar", "Ölçümler", "Abonelikler", "Dersler"],
    techSpecs: mobileSpecs("React Native 0.74"),
    requirements: "React Native geliştirme ortamı, Node.js API",
    basePrice: 3590000,
    technologies: ["react-native", "nodejs", "postgresql"],
    platforms: ["android", "ios"],
    designStyle: "koyu",
    deliveryDays: 6,
    hasAdminPanel: true,
    hasPayment: true,
    salesCount: 38,
    viewCount: 2610,
    licenses: { genisletilmis: 2600000, ozel: 10500000 },
  },
  {
    slug: "hasta-takip-sistemi",
    name: "Hasta Takip Sistemi",
    type: "app",
    category: "klinik-hasta-takip",
    shortDesc: "Klinikler için hasta kaydı, tedavi planı ve tahsilat takibi.",
    description:
      "Hasta Takip Sistemi, kliniklerin hasta dosyalarını, tedavi planlarını ve ödemelerini tek yerde toplar. Randevu, tedavi geçmişi, görsel arşivi ve tahsilat modülleri içerir. Yetkilendirme hekim, asistan ve muhasebe rollerine göre ayrılmıştır.",
    features: ["Hasta dosyası ve geçmişi", "Tedavi planı", "Görsel arşivi", "Tahsilat ve taksit takibi", "Rol bazlı yetkilendirme", "Randevu entegrasyonu"],
    useCases: ["Diş klinikleri", "Estetik merkezleri", "Fizik tedavi klinikleri"],
    modules: ["Hastalar", "Randevular", "Tedaviler", "Tahsilat", "Raporlar", "Kullanıcılar"],
    techSpecs: nextSpecs({ Güvenlik: "Rol bazlı yetki, işlem kayıtları (audit log)" }),
    requirements: "Node.js 20+, PostgreSQL 14+",
    basePrice: 5990000,
    comparePrice: 7200000,
    technologies: ["nextjs", "react", "postgresql"],
    platforms: ["web", "pwa"],
    designStyle: "kurumsal",
    deliveryDays: 8,
    hasAdminPanel: true,
    salesCount: 19,
    viewCount: 2450,
    licenses: { genisletilmis: 4200000, ozel: 16500000 },
  },
  {
    slug: "pusula-crm-sistemi",
    name: "Pusula CRM Sistemi",
    type: "webapp",
    category: "crm-sistemleri",
    shortDesc: "Satış hunisi, teklif yönetimi ve görev takibi olan CRM.",
    description:
      "Pusula, satış ekiplerinin müşteri adaylarını takip etmesi için tasarlanmış bir web uygulamasıdır. Sürükle-bırak satış hunisi, teklif oluşturma, görev ve hatırlatma yönetimi içerir. Tüm iletişim kayıtları müşteri kartında birleşir.",
    features: ["Sürükle-bırak satış hunisi", "Teklif oluşturma ve PDF çıktısı", "Görev ve hatırlatmalar", "Aktivite geçmişi", "Ekip performans raporları", "Rol bazlı yetkilendirme"],
    useCases: ["Satış ekipleri", "Ajanslar ve danışmanlıklar", "B2B hizmet firmaları"],
    modules: ["Müşteriler", "Fırsatlar", "Teklifler", "Görevler", "Raporlar", "Kullanıcılar"],
    techSpecs: nextSpecs(),
    requirements: "Node.js 20+, PostgreSQL 14+",
    basePrice: 4290000,
    technologies: ["nextjs", "react", "postgresql", "nodejs"],
    platforms: ["web"],
    designStyle: "minimal",
    deliveryDays: 5,
    hasAdminPanel: true,
    isNew: true,
    salesCount: 41,
    viewCount: 3480,
    licenses: { genisletilmis: 3100000, ozel: 12500000 },
  },
  {
    slug: "depo-stok-siparis-yonetimi",
    name: "Depo Stok ve Sipariş Yönetimi",
    type: "webapp",
    category: "stok-siparis-yonetimi",
    shortDesc: "Çoklu depo, barkod ve kritik stok uyarısı olan yönetim sistemi.",
    description:
      "Depo, ürün stoklarını birden fazla lokasyonda takip etmek için geliştirilmiştir. Barkod okuyucu desteği, kritik stok uyarıları, transfer ve sayım işlemleri içerir. Farklı satış kanallarınızdan gelen siparişleri tek ekranda toplar.",
    features: ["Çoklu depo takibi", "Barkod desteği", "Kritik stok uyarısı", "Depo transferi ve sayım", "Tedarikçi ve satın alma", "Stok hareket raporları"],
    useCases: ["Toptancı ve distribütörler", "Üretim işletmeleri", "Çok kanallı satış yapan mağazalar"],
    modules: ["Ürünler", "Depolar", "Stok hareketleri", "Siparişler", "Tedarikçiler", "Raporlar"],
    techSpecs: nextSpecs(),
    requirements: "Node.js 20+, PostgreSQL 14+",
    basePrice: 4690000,
    comparePrice: 5590000,
    technologies: ["nextjs", "react", "postgresql"],
    platforms: ["web", "masaustu"],
    designStyle: "kurumsal",
    deliveryDays: 6,
    hasAdminPanel: true,
    salesCount: 33,
    viewCount: 2760,
    licenses: { genisletilmis: 3400000, ozel: 13500000 },
  },

  // ---------------------------- Dijital hizmet paketleri ----------------------------
  {
    slug: "baslangic-dijital-paketi",
    name: "Başlangıç Dijital Paketi",
    type: "service",
    category: "dijital-hizmet-paketleri",
    shortDesc: "Yeni işletmeler için site kurulumu, logo ve temel SEO.",
    description:
      "Başlangıç paketi, dijitalde ilk adımını atan işletmeler içindir. Hazır bir web sitesinin kurulumu, logo tasarımı, temel SEO ayarları ve işletme profili kurulumu bu pakete dahildir. Teslimden sonra bir ay boyunca soru-cevap desteği verilir.",
    features: ["Hazır site kurulumu", "Logo tasarımı", "Temel SEO ayarları", "İşletme profili kurulumu", "1 ay soru-cevap desteği"],
    useCases: ["Yeni kurulan işletmeler", "Şahıs firmaları", "Küçük ölçekli hizmet sağlayıcılar"],
    modules: ["Kurulum", "Tasarım", "SEO", "Destek"],
    techSpecs: { Kapsam: "Tek seferlik hizmet", "Teslim süresi": "7 iş günü", Revizyon: "2 tur", Destek: "1 ay" },
    basePrice: 1890000,
    technologies: [],
    platforms: ["web"],
    designStyle: "kurumsal",
    deliveryDays: 7,
    includesSetup: true,
    isBestSeller: true,
    salesCount: 174,
    viewCount: 5980,
    licenses: { genisletilmis: 900000, ozel: 3500000 },
  },
  {
    slug: "profesyonel-buyume-paketi",
    name: "Profesyonel Büyüme Paketi",
    type: "service",
    category: "dijital-hizmet-paketleri",
    shortDesc: "İçerik, SEO ve reklam yönetimi içeren 3 aylık büyüme programı.",
    description:
      "Profesyonel paket, kurulan siteyi büyüten üç aylık bir programdır. Aylık içerik üretimi, teknik SEO iyileştirmeleri, arama ve sosyal medya reklam yönetimi ile aylık raporlama içerir. Reklam bütçesi pakete dahil değildir; doğrudan platformlara ödenir.",
    features: ["Aylık 4 içerik üretimi", "Teknik SEO iyileştirmeleri", "Arama ağı reklam yönetimi", "Sosyal medya reklam yönetimi", "Aylık performans raporu"],
    useCases: ["Büyüme hedefleyen KOBİ'ler", "E-ticaret markaları", "Hizmet sektörü firmaları"],
    modules: ["İçerik", "SEO", "Reklam", "Raporlama"],
    techSpecs: { Kapsam: "3 aylık program", Raporlama: "Aylık", "Reklam bütçesi": "Dahil değil", Destek: "Program boyunca" },
    basePrice: 5400000,
    comparePrice: 6300000,
    technologies: [],
    platforms: ["web"],
    designStyle: "premium",
    deliveryDays: 5,
    includesSetup: true,
    isFeatured: true,
    salesCount: 68,
    viewCount: 3940,
    licenses: { genisletilmis: 2400000, ozel: 8900000 },
  },
  {
    slug: "kurumsal-dijital-donusum-paketi",
    name: "Kurumsal Dijital Dönüşüm Paketi",
    type: "service",
    category: "dijital-hizmet-paketleri",
    shortDesc: "Özel yazılım, kurumsal kimlik ve 12 aylık destek içeren paket.",
    description:
      "Kurumsal paket, süreçlerini dijitalleştirmek isteyen orta ve büyük ölçekli firmalar için hazırlanır. İhtiyaç analizi, özel yazılım geliştirme, kurumsal kimlik uyarlaması ve 12 aylık teknik destek içerir. Kesin kapsam ve süre analiz sonrası netleştirilir.",
    features: ["İhtiyaç analizi ve yol haritası", "Özel yazılım geliştirme", "Kurumsal kimlik uyarlaması", "Ekip eğitimi", "12 ay teknik destek", "Projeye özel geliştirici ekip"],
    useCases: ["Orta ve büyük ölçekli firmalar", "Çok şubeli işletmeler", "Süreç dijitalleştirme projeleri"],
    modules: ["Analiz", "Geliştirme", "Eğitim", "Destek"],
    techSpecs: { Kapsam: "Analize göre belirlenir", "Başlangıç süresi": "10 iş günü", Destek: "12 ay", Sözleşme: "Proje bazlı" },
    basePrice: 14900000,
    technologies: [],
    platforms: ["web", "ozel-yazilim"],
    designStyle: "premium",
    deliveryDays: 30,
    includesSetup: true,
    isFeatured: true,
    salesCount: 12,
    viewCount: 2890,
    licenses: { genisletilmis: 4900000, ozel: 19900000 },
  },
  {
    slug: "seo-hizmet-paketi",
    name: "SEO Hizmet Paketi",
    type: "service",
    category: "dijital-hizmet-paketleri",
    shortDesc: "Teknik SEO, içerik ve optimizasyon çalışmasını kapsayan aylık paket.",
    description:
      "SEO paketi, organik trafiğinizi artırmaya odaklanır. Teknik denetim, anahtar kelime araştırması, içerik planı ve aylık raporlama içerir. İlk ayda tam denetim raporu teslim edilir.",
    features: ["Teknik SEO denetimi", "Anahtar kelime araştırması", "Aylık içerik planı", "Site içi optimizasyon", "Aylık sıralama raporu"],
    useCases: ["Organik trafik hedefleyen siteler", "E-ticaret kategori sayfaları", "Yerel işletmeler"],
    modules: ["Denetim", "İçerik", "Optimizasyon", "Raporlama"],
    techSpecs: { Kapsam: "Aylık hizmet", "İlk teslim": "Denetim raporu (10 gün)", Raporlama: "Aylık", "Minimum süre": "3 ay" },
    basePrice: 1290000,
    technologies: [],
    platforms: ["web"],
    designStyle: "minimal",
    deliveryDays: 10,
    salesCount: 88,
    viewCount: 4210,
    licenses: { genisletilmis: 700000, ozel: 2900000 },
  },
  {
    slug: "sosyal-medya-yonetim-paketi",
    name: "Sosyal Medya Yönetim Paketi",
    type: "service",
    category: "dijital-hizmet-paketleri",
    shortDesc: "Aylık içerik üretimi, paylaşım planı ve topluluk yönetimi.",
    description:
      "Sosyal medya paketi, markanızın sosyal medya hesaplarını düzenli yönetir. Aylık 12 görsel veya video içerik, paylaşım takvimi ve yorum-mesaj yönetimi içerir. İçerik onayı her zaman sizde kalır.",
    features: ["Aylık 12 içerik üretimi", "Paylaşım takvimi", "Topluluk yönetimi", "Aylık performans raporu", "Trend takibi"],
    useCases: ["Perakende markaları", "Restoran ve kafeler", "Kişisel markalar"],
    modules: ["İçerik", "Takvim", "Topluluk", "Raporlama"],
    techSpecs: { Kapsam: "Aylık hizmet", "Platform sayısı": "3", "İçerik adedi": "12/ay", "Minimum süre": "3 ay" },
    basePrice: 1690000,
    comparePrice: 1990000,
    technologies: [],
    platforms: ["web"],
    designStyle: "renkli",
    deliveryDays: 7,
    salesCount: 105,
    viewCount: 4630,
    licenses: { genisletilmis: 800000, ozel: 3200000 },
  },
  {
    slug: "saglik-turizmi-dijital-paketi",
    name: "Sağlık Turizmi Dijital Paketi",
    type: "service",
    category: "dijital-hizmet-paketleri",
    shortDesc: "Çok dilli site, hasta adayı toplama ve reklam yönetimi.",
    description:
      "Sağlık turizmi paketi, yurt dışından hasta adayı toplamak isteyen klinikler için hazırlanmıştır. Çok dilli site kurulumu, hasta adayı formu, WhatsApp entegrasyonu ve hedef ülkelere yönelik reklam yönetimi içerir. Tüm formlar KVKK ve GDPR onay metinleriyle gelir.",
    features: ["Çok dilli site kurulumu (TR/EN/AR/DE)", "Hasta adayı formu ve CRM aktarımı", "WhatsApp entegrasyonu", "Hedef ülke reklam yönetimi", "Aylık dönüşüm raporu"],
    useCases: ["Saç ekim merkezleri", "Diş ve estetik klinikleri", "Göz ve obezite cerrahisi merkezleri"],
    modules: ["Site kurulumu", "Form ve CRM", "Reklam", "Raporlama"],
    techSpecs: { Kapsam: "Kurulum + aylık yönetim", Diller: "TR / EN / AR / DE", "İlk teslim": "15 iş günü", "Reklam bütçesi": "Dahil değil" },
    basePrice: 8900000,
    technologies: [],
    platforms: ["web"],
    designStyle: "premium",
    deliveryDays: 15,
    includesSetup: true,
    multiLanguage: true,
    isNew: true,
    salesCount: 21,
    viewCount: 3170,
    licenses: { genisletilmis: 3900000, ozel: 14900000 },
  },
];
